baseURL = 'https://defingo.net/'
languageCode = 'en-us'
title = 'Defingo.net - Personal website for William E. Whitaker, Jr'
theme = 'LoveIt'
defaultContentLanguage = 'en'
defaultTheme = 'auto'
enableEmoji = true
enableRobotsTXT = true

[author]
  name = 'William E. Whitaker, Jr'
  email = 'witty.book0848@fastmail.com'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/pages/projects/'
    weight = 2
  [[menu.main]]
    identifier = 'resources'
    name = 'Resources'
    url = '/pages/resources/'
    weight = 3
  [[menu.main]]
    identifier = 'gallery'
    name = 'Gallery'
    url = '/pages/gallery/'
    weight = 4
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/pages/about/'
    weight = 5

[params]
  description = 'I am an information systems professional with broad background in network support, system administration and software development focused on security topics.'
  
  [params.author]
    name = 'wew'
    email = 'witty.book0848@fastmail.com'
  
  [params.header]
    [params.header.title]
      logo = '/favicon-32x32.png'
      name = 'defingo.net'
  
  [params.home]
    rss = 3 
    
    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.png"
      subtitle = "I manage networks and services"
    
    [params.home.posts]
      enable = false

  [params.page]
    [params.page.share]
      enable = true
      X = true
      Linkedin = true
      Facebook = true
      Reddit = true
      Threads = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Diaspora = false
      Mix = false
      Telegram = false

    [params.page.comment]
      enable = true

      [params.page.comment.utterances]
      enable = true
      repo = "wwhitaker/hugo-loveit"
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"

  [params.social]
    Instagram = 'wewhitaker'
    GitHub = 'wwhitaker'
    X = 'wewhitaker'
    LinkedIn = 'wewhitaker'

  [params.seo]
    image = '/images/og-image.png'
